import { CurrencyPipe, DatePipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatButtonToggleModule } from '@angular/material/button-toggle';
import { MatIconModule } from '@angular/material/icon';
import { AuthService } from '../../../../core/auth/auth.service';
import { MockDatabaseService } from '../../../../core/services/mock-database.service';
import { EmptyStateComponent } from '../../../../shared/components/empty-state/empty-state.component';
import { ErrorStateComponent } from '../../../../shared/components/error-state/error-state.component';
import { LoadingStateComponent } from '../../../../shared/components/loading-state/loading-state.component';
import { PageHeaderComponent } from '../../../../shared/components/page-header/page-header.component';
import { StatusChipComponent } from '../../../../shared/components/status-chip/status-chip.component';
import { DashboardView } from '../../models/dashboard.models';
import { DashboardService } from '../../services/dashboard.service';

@Component({selector:'app-dashboard',standalone:true,imports:[CurrencyPipe,DatePipe,RouterLink,MatButtonModule,MatButtonToggleModule,MatIconModule,EmptyStateComponent,ErrorStateComponent,LoadingStateComponent,PageHeaderComponent,StatusChipComponent],
template:`<app-page-header eyebrow="Visão geral" [title]="'Bom dia, '+firstName" subtitle="Acompanhe o movimento da loja e o resultado do período."/><div class="period-bar"><mat-button-toggle-group [value]="period()" (change)="changePeriod($event.value)" aria-label="Período do dashboard"><mat-button-toggle value="today">Hoje</mat-button-toggle><mat-button-toggle value="7d">Últimos 7 dias</mat-button-toggle><mat-button-toggle value="month">Este mês</mat-button-toggle><mat-button-toggle value="custom">Personalizado</mat-button-toggle></mat-button-toggle-group>@if(period()==='custom'){<div class="custom-dates"><input type="date" aria-label="Data inicial" [value]="customStart()" (change)="customStart.set($any($event.target).value)"><span>até</span><input type="date" aria-label="Data final" [value]="customEnd()" (change)="customEnd.set($any($event.target).value)"><button mat-stroked-button (click)="reload()">Aplicar</button></div>}<span class="updated"><mat-icon>schedule</mat-icon>Atualizado agora</span></div>
@if(loading()){<section class="surface"><app-loading-state label="Carregando indicadores…"/></section>}@else if(error()){<app-error-state title="Dashboard indisponível" message="Não foi possível consolidar os dados deste período."/><div class="retry"><button mat-stroked-button (click)="reload()">Tentar novamente</button></div>}@else if(view()){<section class="cards-grid metrics" aria-label="Indicadores principais">@for(metric of metrics();track metric.label){<article class="surface metric-card" [class.featured]="metric.featured"><div class="metric-top"><span>{{metric.label}}</span><span class="metric-icon"><mat-icon>{{metric.icon}}</mat-icon></span></div><strong>{{metric.money?(metric.value|currency:'BRL':'symbol':'1.2-2':'pt-BR'):metric.value}}</strong><small>{{metric.note}}</small></article>}</section>
<div class="dash-grid"><section class="surface chart-card"><div class="surface-header"><div><h2>Faturamento por dia</h2><span class="cell-meta">Valores brutos do período</span></div><strong>{{view()!.summary.revenue|currency:'BRL':'symbol':'1.2-2':'pt-BR'}}</strong></div><div class="chart" role="img" aria-label="Gráfico de faturamento diário">@for(point of view()!.daily;track point.day){<div class="bar-col"><span class="bar-value">{{point.value|currency:'BRL':'symbol':'1.0-0':'pt-BR'}}</span><div class="bar" [style.height.%]="point.value/maxRevenue()*100"></div><b>{{point.day}}</b></div>}</div></section><section class="surface origin-card"><div class="surface-header"><h2>Vendas por origem</h2></div><div class="surface-body origins">@for(origin of origins();track origin.name){<div><span class="origin-icon"><mat-icon>{{origin.icon}}</mat-icon></span><div><strong>{{origin.name}}</strong><small>{{origin.count}} vendas</small></div><b>{{origin.share}}%</b></div>}</div></section></div>
<div class="dash-grid bottom"><section class="surface"><div class="surface-header"><h2>Vendas recentes</h2><a mat-button routerLink="/app/vendas/historico">Ver histórico <mat-icon>arrow_forward</mat-icon></a></div>@if(!db.sales().length){<app-empty-state icon="receipt_long" title="Nenhuma venda encontrada" message="As vendas concluídas aparecerão aqui."/>}@else{<div class="table-wrap"><table class="data-table"><thead><tr><th>Venda</th><th>Horário</th><th>Origem</th><th>Valor líquido</th><th>Status</th></tr></thead><tbody>@for(sale of db.sales().slice(0,4);track sale.id){<tr><td class="cell-title">{{sale.number}}</td><td>{{sale.createdAt|date:'HH:mm'}}</td><td>{{sale.origin==='COUNTER'?'Balcão':sale.origin}}</td><td class="money">{{sale.net|currency:'BRL':'symbol':'1.2-2':'pt-BR'}}</td><td><app-status-chip [status]="sale.status"/></td></tr>}</tbody></table></div>}</section><section class="surface flow-card"><div class="surface-header"><h2>Entradas e saídas</h2></div><div class="surface-body"><div class="flow-row in"><span><mat-icon>south_west</mat-icon></span><div><small>Entradas</small><strong>{{view()!.summary.revenue|currency:'BRL':'symbol':'1.2-2':'pt-BR'}}</strong></div></div><div class="flow-row out"><span><mat-icon>north_east</mat-icon></span><div><small>Despesas + taxas</small><strong>{{(view()!.summary.expenses+view()!.summary.ifoodFees+view()!.summary.food99Fees)|currency:'BRL':'symbol':'1.2-2':'pt-BR'}}</strong></div></div><div class="result"><span>Resultado estimado</span><strong>{{view()!.summary.estimatedResult|currency:'BRL':'symbol':'1.2-2':'pt-BR'}}</strong></div></div></section></div>}`,
styles:[`.period-bar{display:flex;align-items:center;gap:14px;margin:-8px 0 20px;flex-wrap:wrap}.updated{margin-left:auto;color:var(--muted);font-size:.72rem;display:flex;align-items:center;gap:5px}.updated mat-icon{font-size:17px;width:17px;height:17px}.custom-dates{display:flex;align-items:center;gap:8px}.custom-dates input{border:1px solid var(--border);padding:8px;border-radius:8px}.metrics{grid-template-columns:repeat(6,1fr);margin-bottom:18px}.metric-card.featured{background:var(--yellow-light);border-color:#f2d66d}.dash-grid{display:grid;grid-template-columns:1.65fr .75fr;gap:18px;margin-bottom:18px}.chart{height:260px;padding:36px 24px 20px;display:flex;align-items:flex-end;gap:clamp(8px,2vw,24px)}.bar-col{height:100%;flex:1;display:flex;flex-direction:column;justify-content:flex-end;align-items:center;gap:7px}.bar{width:min(42px,75%);min-height:8px;border-radius:7px 7px 2px 2px;background:var(--red)}.bar-col:nth-child(even) .bar{background:#d15a50}.bar-value{font-size:.64rem;color:var(--muted)}.bar-col b{font-size:.7rem;color:var(--muted)}.origins{display:grid;gap:20px}.origins>div{display:grid;grid-template-columns:auto 1fr auto;gap:10px;align-items:center}.origin-icon{width:36px;height:36px;border-radius:9px;display:grid;place-items:center;background:#fff0ee;color:var(--red)}.origins strong,.origins small{display:block;font-size:.78rem}.origins small{color:var(--muted);margin-top:2px}.origins>b{font-size:.82rem}.bottom{grid-template-columns:1.4fr .7fr}.flow-row{display:flex;gap:12px;align-items:center;padding:12px 0;border-bottom:1px solid var(--border)}.flow-row>span{width:36px;height:36px;border-radius:9px;display:grid;place-items:center}.flow-row.in>span{background:#eaf5eb;color:var(--success)}.flow-row.out>span{background:#fff0ee;color:var(--red)}.flow-row small,.flow-row strong{display:block}.flow-row small{color:var(--muted);font-size:.7rem}.result{display:flex;justify-content:space-between;padding:15px;margin-top:14px;border-radius:9px;background:var(--yellow-light);font-size:.8rem}.result strong{color:var(--red-dark)}.retry{text-align:center;margin-top:12px}@media(max-width:1250px){.metrics{grid-template-columns:repeat(3,1fr)}}@media(max-width:900px){.dash-grid{grid-template-columns:1fr}.metrics{grid-template-columns:repeat(2,1fr)}}@media(max-width:550px){.metrics{grid-template-columns:1fr}.updated{margin-left:0}.chart{padding-inline:8px}.bar-value{display:none}.custom-dates{flex-wrap:wrap}}`],changeDetection:ChangeDetectionStrategy.OnPush})
export class DashboardComponent {
  private readonly service=inject(DashboardService);private readonly auth=inject(AuthService);readonly db=inject(MockDatabaseService);
  readonly firstName=this.auth.currentUser()?.name.split(' ')[0]??'Fabiana';readonly period=signal('today');readonly customStart=signal('2026-09-01');readonly customEnd=signal('2026-09-15');readonly loading=signal(true);readonly error=signal(false);readonly view=signal<DashboardView|null>(null);
  readonly metrics=computed(()=>{const s=this.view()!.summary;return[{label:'Faturamento',value:s.revenue,money:true,icon:'payments',note:`${s.salesCount} vendas no período`},{label:'Despesas',value:s.expenses,money:true,icon:'receipt_long',note:'Saídas registradas'},{label:'Taxas do iFood',value:s.ifoodFees,money:true,icon:'percent',note:`${s.ifoodSales} venda(s)`},{label:'Taxas da 99Food',value:s.food99Fees,money:true,icon:'percent',note:`${s.food99Sales} venda(s)`},{label:'Resultado estimado',value:s.estimatedResult,money:true,icon:'trending_up',note:'Após despesas e taxas',featured:true},{label:'Quantidade de vendas',value:s.salesCount,money:false,icon:'shopping_cart',note:'Todos os canais'}]});
  readonly origins=computed(()=>{const s=this.view()!.summary;const total=Math.max(1,s.salesCount);return[{name:'Balcão',count:s.counterSales,share:Math.round(s.counterSales/total*100),icon:'storefront'},{name:'iFood',count:s.ifoodSales,share:Math.round(s.ifoodSales/total*100),icon:'moped'},{name:'99Food',count:s.food99Sales,share:Math.round(s.food99Sales/total*100),icon:'delivery_dining'}]});readonly maxRevenue=computed(()=>Math.max(...(this.view()?.daily.map(point=>point.value)??[1])));
  constructor(){void this.reload();}async changePeriod(value:string){this.period.set(value);if(value!=='custom')await this.reload();}async reload(){if(this.period()==='custom'&&(!this.customStart()||!this.customEnd()||this.customStart()>this.customEnd()))return;this.loading.set(true);this.error.set(false);try{this.view.set(await this.service.load(this.period(),this.customStart(),this.customEnd()));}catch{this.error.set(true);}finally{this.loading.set(false);}}
}
