import { CurrencyPipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MAT_DIALOG_DATA, MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { MatIconModule } from '@angular/material/icon';
import { Sale } from '../../../../core/models/domain.models';

@Component({selector:'app-sale-success-dialog',standalone:true,imports:[CurrencyPipe,MatButtonModule,MatDialogModule,MatIconModule],template:`<div class="success-dialog"><span class="success-icon"><mat-icon>check_circle</mat-icon></span><p class="eyebrow">Operação concluída</p><h2>Venda realizada com sucesso</h2><p>A venda <strong>{{data.number}}</strong> foi registrada, o pagamento confirmado e o estoque atualizado.</p><div class="total"><span>Total</span><strong>{{data.net|currency:'BRL':'symbol':'1.2-2':'pt-BR'}}</strong></div><footer><button mat-stroked-button (click)="ref.close('VIEW')"><mat-icon>receipt_long</mat-icon>Visualizar venda</button><button mat-flat-button class="primary-button" (click)="ref.close('NEW')"><mat-icon>add_shopping_cart</mat-icon>Nova venda</button></footer></div>`,styles:[`.success-dialog{width:min(480px,88vw);padding:28px;text-align:center}.success-icon{width:58px;height:58px;border-radius:50%;display:grid;place-items:center;margin:0 auto 12px;background:#eaf5eb;color:var(--success)}.success-icon mat-icon{font-size:34px;width:34px;height:34px}h2{font-size:1.35rem;margin:5px 0 8px}.success-dialog>p:not(.eyebrow){color:var(--muted);font-size:.82rem;line-height:1.5}.total{display:flex;justify-content:space-between;align-items:center;background:var(--yellow-light);padding:14px 16px;border-radius:10px;margin:20px 0}.total strong{font-size:1.3rem;color:var(--red-dark)}footer{display:flex;justify-content:center;gap:9px;flex-wrap:wrap}`],changeDetection:ChangeDetectionStrategy.OnPush})
export class SaleSuccessDialogComponent{readonly data=inject<Sale>(MAT_DIALOG_DATA);readonly ref=inject(MatDialogRef<SaleSuccessDialogComponent>);}
