import { CurrencyPipe, DatePipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { AuthService } from '../../../../core/auth/auth.service';
import { EmptyStateComponent } from '../../../../shared/components/empty-state/empty-state.component';
import { PageHeaderComponent } from '../../../../shared/components/page-header/page-header.component';
import { SearchInputComponent } from '../../../../shared/components/search-input/search-input.component';
import { StockLevelComponent } from '../../components/stock-level/stock-level.component';
import { InventoryService } from '../../services/inventory.service';

@Component({selector:'app-inventory-list',standalone:true,imports:[CurrencyPipe,DatePipe,RouterLink,MatButtonModule,MatIconModule,EmptyStateComponent,PageHeaderComponent,SearchInputComponent,StockLevelComponent],template:`<app-page-header eyebrow="Estoque" title="Posição de estoque" subtitle="Consulte quantidades e a origem da última movimentação."/><div class="toolbar"><app-search-input placeholder="Buscar produto" [value]="query()" (changed)="query.set($event)"/>@if(auth.isAdmin()){<a mat-stroked-button routerLink="/app/estoque/pereciveis"><mat-icon>event_available</mat-icon>Perecíveis</a><a mat-flat-button class="primary-button" routerLink="/app/estoque/ajustes"><mat-icon>tune</mat-icon>Novo ajuste</a>}</div><section class="surface"><div class="surface-header"><div><h2>Produtos em estoque</h2><span class="cell-meta">{{filtered().length}} itens cadastrados</span></div></div>@if(!filtered().length){<app-empty-state icon="inventory_2" title="Nenhum produto encontrado" message="Ajuste a pesquisa para consultar o estoque."/>}@else{<div class="table-wrap"><table class="data-table"><thead><tr><th>Produto</th><th>Estoque atual</th><th>Custo</th><th>Última movimentação</th><th>Origem</th>@if(auth.isAdmin()){<th>Ação</th>}</tr></thead><tbody>@for(p of filtered();track p.id){<tr><td><div class="cell-title">{{p.name}}</div><div class="cell-meta">{{p.category}}</div></td><td><app-stock-level [quantity]="p.stock" [unit]="p.unit"/></td><td>{{p.cost|currency:'BRL':'symbol':'1.2-2':'pt-BR'}}</td><td>{{lastMovement(p.id)?.date?(lastMovement(p.id)!.date|date:'dd/MM/yyyy HH:mm'):'15/09/2026 08:00'}}</td><td>{{lastMovement(p.id)?.origin??'Saldo inicial'}}</td>@if(auth.isAdmin()){<td><a mat-button [routerLink]="['/app/estoque/ajustes']" [queryParams]="{produto:p.id}">Ajustar <mat-icon>chevron_right</mat-icon></a></td>}</tr>}</tbody></table></div>}</section>`,changeDetection:ChangeDetectionStrategy.OnPush})
export class InventoryListComponent{readonly service=inject(InventoryService);readonly auth=inject(AuthService);readonly query=signal('');readonly filtered=computed(()=>this.service.products().filter(product=>product.name.toLowerCase().includes(this.query().toLowerCase())));lastMovement(id:string){return this.service.movements().find(movement=>movement.productId===id);}}
