import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { Router } from '@angular/router';
import { MatDialog } from '@angular/material/dialog';
import { MatSnackBar } from '@angular/material/snack-bar';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { Product } from '../../../../core/models/domain.models';
import { ConfirmationDialogComponent } from '../../../../shared/components/confirmation-dialog/confirmation-dialog.component';
import { PageHeaderComponent } from '../../../../shared/components/page-header/page-header.component';
import { PaymentDialogComponent } from '../../components/payment-dialog/payment-dialog.component';
import { ProductGridComponent } from '../../components/product-grid/product-grid.component';
import { ProductSearchComponent } from '../../components/product-search/product-search.component';
import { SaleCartComponent } from '../../components/sale-cart/sale-cart.component';
import { SaleSuccessDialogComponent } from '../../components/sale-success-dialog/sale-success-dialog.component';
import { PaymentRequest } from '../../models/sales.models';
import { SalesService } from '../../services/sales.service';

@Component({selector:'app-new-sale',standalone:true,imports:[MatButtonModule,MatIconModule,PageHeaderComponent,ProductGridComponent,ProductSearchComponent,SaleCartComponent],template:`<div class="pdv-heading"><app-page-header eyebrow="Vendas / PDV" title="Nova venda" subtitle="Adicione os produtos e finalize o pagamento."/><div class="cash-open" [class.closed]="!sales.cashOpen()"><span></span><div><strong>{{sales.cashOpen()?'Caixa aberto':'Caixa fechado'}}</strong><small>{{sales.cashOpen()?'pronto para vender':'abra o caixa para concluir'}}</small></div></div></div>@if(message()){<div class="notice" [class.error]="messageTone()==='error'" [class.success]="messageTone()==='success'" role="status"><mat-icon>{{messageTone()==='error'?'error':'check_circle'}}</mat-icon>{{message()}}</div>}<div class="pdv-layout"><section><app-product-search [query]="query()" (queryChange)="query.set($event)" (barcodeAdd)="addBarcode($event)"/><app-product-grid [title]="query()?'Resultados da pesquisa':'Produtos frequentes'" [products]="visibleProducts()" (selected)="add($event)"/></section><app-sale-cart [items]="sales.cart()" [total]="sales.total()" [itemCount]="sales.itemCount()" (increase)="quantity($event,1)" (decrease)="quantity($event,-1)" (remove)="sales.remove($event)" (cancel)="cancel()" (pay)="pay()"/></div>`,styles:[`.pdv-heading{display:flex;justify-content:space-between;align-items:flex-start}.pdv-heading app-page-header{flex:1}.cash-open{display:flex;gap:9px;align-items:center;background:#eaf5eb;border:1px solid #cee6d0;color:#1e6424;border-radius:10px;padding:9px 13px}.cash-open.closed{background:#fff0ee;border-color:#efcbc6;color:var(--red-dark)}.cash-open>span{width:8px;height:8px;border-radius:50%;background:var(--success)}.cash-open.closed>span{background:var(--red)}.cash-open strong,.cash-open small{display:block;font-size:.72rem}.cash-open small{color:inherit;opacity:.75;margin-top:2px}.pdv-layout{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(355px,.72fr);gap:20px}.notice{margin-top:-8px}@media(max-width:1080px){.pdv-layout{grid-template-columns:1fr}.pdv-heading{flex-direction:column}.cash-open{margin:-12px 0 18px}}`],changeDetection:ChangeDetectionStrategy.OnPush})
export class NewSaleComponent {
  readonly sales=inject(SalesService);private readonly dialog=inject(MatDialog);private readonly snack=inject(MatSnackBar);private readonly router=inject(Router);
  readonly query=signal('');readonly message=signal('');readonly messageTone=signal<'error'|'success'>('success');
  readonly visibleProducts=computed(()=>{const items=this.sales.findProducts(this.query());return this.query()?items:items.filter(product=>product.frequent).slice(0,6);});
  add(product:Product){try{this.sales.addProduct(product);this.setMessage(`${product.name} adicionado à venda.`,'success');}catch(error){this.handleError(error);}}
  addBarcode(code:string){if(!code.trim()){this.setMessage('Digite ou leia um código de barras.','error');return;}try{this.sales.addByBarcode(code.trim());this.setMessage('Produto adicionado pelo código de barras.','success');}catch(error){this.handleError(error);}}
  quantity(id:string,delta:number){try{this.sales.changeQuantity(id,delta);}catch(error){this.handleError(error);}}
  cancel(){if(!this.sales.cart().length)return;this.dialog.open(ConfirmationDialogComponent,{data:{title:'Cancelar venda em andamento?',message:'Todos os itens serão removidos. Esta ação não afeta o estoque.',confirmLabel:'Cancelar venda',destructive:true},width:'430px'}).afterClosed().subscribe(ok=>{if(ok){this.sales.cancel();this.snack.open('Venda cancelada.','Fechar',{duration:3000});}});}
  pay(){if(!this.sales.cashOpen()){this.setMessage('O caixa está fechado. Abra o caixa antes de finalizar a venda.','error');return;}if(!this.sales.cart().length){this.setMessage('O carrinho está vazio.','error');return;}this.dialog.open(PaymentDialogComponent,{data:{total:this.sales.total(),items:this.sales.cart()},disableClose:true}).afterClosed().subscribe(async(request:PaymentRequest|undefined)=>{if(!request)return;try{const sale=await this.sales.complete(request);this.dialog.open(SaleSuccessDialogComponent,{data:sale,disableClose:true}).afterClosed().subscribe(action=>{if(action==='VIEW')void this.router.navigate(['/app/vendas',sale.id]);else{this.query.set('');this.setMessage('Pronto para uma nova venda.','success');}});}catch(error){this.handleError(error);}});}
  private handleError(error:unknown){const code=error instanceof Error?error.message:'';const text:Record<string,string>={PRODUCT_NOT_FOUND:'Produto não encontrado.',INSUFFICIENT_STOCK:'Estoque insuficiente para a quantidade solicitada.',INVALID_QUANTITY:'A quantidade mínima é 1.',EMPTY_CART:'O carrinho está vazio.',INSUFFICIENT_AMOUNT:'O valor recebido é insuficiente.',CASH_CLOSED:'O caixa está fechado. Abra o caixa antes de finalizar a venda.'};this.setMessage(text[code]??'Não foi possível concluir a operação.','error');}
  private setMessage(text:string,tone:'error'|'success'){this.message.set(text);this.messageTone.set(tone);setTimeout(()=>this.message.set(''),4000);}
}
