import { CurrencyPipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatSnackBar } from '@angular/material/snack-bar';
import { PageHeaderComponent } from '../../../../shared/components/page-header/page-header.component';
import { CashService } from '../../services/cash.service';

@Component({ selector:'app-close-cash', standalone:true,
  imports:[CurrencyPipe,ReactiveFormsModule,MatButtonModule,MatFormFieldModule,MatIconModule,MatInputModule,PageHeaderComponent],
  template:`<app-page-header eyebrow="Caixa" title="Fechar caixa" subtitle="Conte o dinheiro e confira a diferença antes de concluir."/><div class="close-grid"><section class="surface surface-body"><h2>Conferência</h2><div class="expected"><span>Saldo esperado</span><strong>{{cash.expected()|currency:'BRL':'symbol':'1.2-2':'pt-BR'}}</strong></div><form [formGroup]="form" (ngSubmit)="close()"><mat-form-field appearance="outline"><mat-label>Valor contado</mat-label><span matTextPrefix>R$&nbsp;</span><input matInput type="number" step="0.01" min="0" formControlName="countedBalance"></mat-form-field><div class="difference" [class.negative]="difference()!==0"><span>Diferença</span><strong>{{difference()|currency:'BRL':'symbol':'1.2-2':'pt-BR'}}</strong></div>@if(difference()!==0){<mat-form-field appearance="outline"><mat-label>Justificativa da diferença</mat-label><textarea matInput rows="3" formControlName="justification" placeholder="Explique o motivo da diferença"></textarea>@if(form.controls.justification.touched&&form.controls.justification.invalid){<mat-error>A justificativa é obrigatória quando há diferença.</mat-error>}</mat-form-field>}<div class="form-actions"><button mat-button type="button" (click)="router.navigate(['/app/caixa/resumo'])">Cancelar</button><button mat-flat-button class="primary-button" type="submit" [disabled]="saving()"><mat-icon>lock</mat-icon>{{saving()?'Fechando…':'Confirmar fechamento'}}</button></div></form></section><aside class="surface surface-body"><h2>Resumo final</h2><dl><div><dt>Saldo inicial</dt><dd>{{cash.register()?.initialBalance|currency:'BRL':'symbol':'1.2-2':'pt-BR'}}</dd></div><div><dt>Vendas em dinheiro</dt><dd>{{cash.cashSales()|currency:'BRL':'symbol':'1.2-2':'pt-BR'}}</dd></div><div><dt>Despesas em dinheiro</dt><dd>- {{cash.cashExpenses()|currency:'BRL':'symbol':'1.2-2':'pt-BR'}}</dd></div><div><dt>Estornos em dinheiro</dt><dd>- {{cash.cashRefunds()|currency:'BRL':'symbol':'1.2-2':'pt-BR'}}</dd></div></dl><div class="notice warning"><mat-icon>info</mat-icon>Após confirmar, o caixa ficará fechado para novas vendas.</div></aside></div>`,
  styles:[`.close-grid{display:grid;grid-template-columns:minmax(0,1fr) 340px;gap:20px;max-width:1000px}.surface h2{font-size:1rem;margin:0 0 18px}.expected{padding:16px;background:var(--yellow-light);border-radius:10px;display:flex;justify-content:space-between;margin-bottom:20px}.expected strong{font-size:1.2rem;color:var(--red-dark)}form{display:grid;gap:10px}.difference{display:flex;justify-content:space-between;border:1px solid var(--border);border-radius:9px;padding:12px 14px;margin:-4px 0 10px}.difference.negative{background:#fff0ee;color:var(--red-dark)}dl{margin:0 0 20px}dl div{display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid var(--border);font-size:.8rem}dt{color:var(--muted)}dd{margin:0;font-weight:700}.form-actions{display:flex;justify-content:flex-end;gap:8px}.notice{font-size:.76rem}@media(max-width:800px){.close-grid{grid-template-columns:1fr}}`], changeDetection:ChangeDetectionStrategy.OnPush })
export class CloseCashComponent {
  readonly cash=inject(CashService); readonly router=inject(Router); private readonly snack=inject(MatSnackBar); readonly saving=signal(false);
  readonly counted = signal(this.cash.expected());
  readonly form=new FormGroup({countedBalance:new FormControl(this.cash.expected(),{nonNullable:true,validators:[Validators.required,Validators.min(0)]}),justification:new FormControl('',{nonNullable:true})});
  constructor(){this.form.controls.countedBalance.valueChanges.subscribe(value=>{this.counted.set(value);this.updateValidator();});}
  difference(){return Math.round((this.counted()-this.cash.expected())*100)/100;}
  updateValidator(){this.form.controls.justification.setValidators(this.difference()!==0?[Validators.required,Validators.minLength(4)]:[]);this.form.controls.justification.updateValueAndValidity({emitEvent:false});}
  async close(){this.updateValidator();if(this.form.invalid){this.form.markAllAsTouched();return;}this.saving.set(true);try{await this.cash.close(this.form.getRawValue());this.snack.open('Caixa fechado com sucesso.','Fechar',{duration:3500});await this.router.navigate(['/app/caixa/resumo']);}finally{this.saving.set(false);}}
}
